import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import Link from 'next/link';
import { db } from '@/lib/db';
import { safeJsonStringify } from '@/lib/utils';
import { ArrowLeft, ArrowRight, Calendar, User, Tag, Clock, ChevronRight, FileText, Sparkles, Eye } from 'lucide-react';
import ReactMarkdown, { type Components } from 'react-markdown';
import { ReadingProgress, ShareButtons, ActiveTocHighlighter, BackToTop } from '@/components/blog-interactions';
import { Newsletter } from '@/components/newsletter';
import { PopularPosts } from '@/components/popular-posts';

type Params = { slug: string };

/** Static metadata per post so each article gets its own OG title/description.
 * The OG image is auto-generated by the `opengraph-image.tsx` route in this
 * folder — Next.js injects it automatically, so we intentionally do NOT set
 * `images` here (that would override the generated image). */
export async function generateMetadata({ params }: { params: Promise<Params> }): Promise<Metadata> {
  const { slug } = await params;
  const post = await db.blogPost.findUnique({ where: { slug } });
  if (!post || !post.published) return { title: 'Article not found' };
  return {
    title: `${post.title} — Systematic Yield Analysts`,
    description: post.excerpt ?? 'Insights from Systematic Yield Analysts',
    openGraph: {
      title: post.title,
      description: post.excerpt ?? '',
      type: 'article',
    },
    twitter: {
      card: 'summary_large_image',
      title: post.title,
      description: post.excerpt ?? '',
    },
    alternates: { canonical: `https://systematicyield.in/blog/${post.slug}` },
  };
}

/** Rough reading-time estimate from Markdown content (~200 wpm). */
function readingTime(content: string): number {
  const words = content.trim().split(/\s+/).length;
  return Math.max(1, Math.round(words / 200));
}

/** Extract H2 headings from Markdown to build a lightweight table of contents. */
function extractToc(content: string): { id: string; text: string }[] {
  const lines = content.split('\n');
  const toc: { id: string; text: string }[] = [];
  for (const line of lines) {
    const m = line.match(/^##\s+(.+?)\s*$/);
    if (m) {
      const text = m[1].replace(/[*_`]/g, '').trim();
      const id = text
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, '')
        .replace(/\s+/g, '-');
      toc.push({ id, text });
    }
  }
  return toc;
}

/** Custom react-markdown renderers: inject id attributes on h2/h3 so the ToC
 *  links and the IntersectionObserver-based active highlighter can target them. */
const markdownComponents: Components = {
  h2: ({ children }) => {
    const text = String(children);
    const id = text
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-');
    return <h2 id={id}>{children}</h2>;
  },
};

export default async function BlogPostPage({ params }: { params: Promise<Params> }) {
  const { slug } = await params;
  const post = await db.blogPost.findUnique({ where: { slug } });

  if (!post || !post.published) notFound();

  // Increment view count (fire-and-forget, non-blocking). Uses a separate
  // try/catch so a view-tracking failure never breaks page render.
  db.blogPost
    .update({ where: { id: post.id }, data: { views: { increment: 1 } } })
    .catch(() => {});

  // Fetch prev/next published posts (by creation date) + related posts (same
  // category, excluding current) for article navigation.
  const [older, newer, related] = await Promise.all([
    db.blogPost.findFirst({
      where: { published: true, createdAt: { lt: post.createdAt } },
      orderBy: { createdAt: 'desc' },
      select: { slug: true, title: true },
    }),
    db.blogPost.findFirst({
      where: { published: true, createdAt: { gt: post.createdAt } },
      orderBy: { createdAt: 'asc' },
      select: { slug: true, title: true },
    }),
    db.blogPost.findMany({
      where: { published: true, category: post.category, slug: { not: post.slug } },
      orderBy: { createdAt: 'desc' },
      take: 3,
      select: {
        id: true, slug: true, title: true, excerpt: true, coverImage: true,
        category: true, author: true, createdAt: true,
      },
    }),
  ]);

  const fmt = (d: Date) =>
    d.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' });
  const mins = readingTime(post.content);
  const toc = extractToc(post.content);
  const canonical = `https://systematicyield.in/blog/${post.slug}`;

  // JSON-LD Article schema for rich results.
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: post.title,
    description: post.excerpt ?? '',
    datePublished: post.createdAt.toISOString(),
    dateModified: post.updatedAt.toISOString(),
    author: { '@type': 'Organization', name: post.author },
    publisher: { '@type': 'Organization', name: 'Systematic Yield Analysts' },
    mainEntityOfPage: canonical,
    image: post.coverImage ? [post.coverImage] : undefined,
  };

  return (
    <article className="min-h-screen bg-cf-bg text-cf-text relative overflow-hidden">
      {/* Ambient gold glow drift */}
      <div
        className="pointer-events-none absolute -top-32 right-0 w-[520px] h-[520px] rounded-full blur-3xl opacity-20 animate-cf-glow-drift"
        style={{ background: 'radial-gradient(circle, rgba(226,177,92,0.14), transparent 70%)' }}
        aria-hidden
      />
      <ReadingProgress />
      <ActiveTocHighlighter />
      <BackToTop />

      {/* Hero */}
      <header className="relative overflow-hidden border-b border-white/[0.06]">
        <div className="wrap relative px-5 py-16 md:px-8 md:py-24">
          <Link
            href="/blog"
            className="mb-8 inline-flex items-center gap-2 text-sm text-cf-mist transition-colors duration-160 hover:text-cf-gold"
          >
            <ArrowLeft className="h-4 w-4" /> All Insights
          </Link>

          <div className="flex flex-wrap items-center gap-3 text-xs animate-cf-reveal-up">
            <Link
              href={`/blog/category/${post.category.toLowerCase().replace(/\s+/g, '-')}`}
              className="inline-flex items-center gap-1.5 rounded-full bg-cf-gold/10 border border-cf-gold/30 px-3 py-1 text-cf-gold backdrop-blur-glass transition-all duration-240 ease-cinematic hover:bg-cf-gold/20 hover:border-cf-gold/50 hover:shadow-glow-gold"
              aria-label={`View all posts in ${post.category}`}
            >
              <Tag className="h-3.5 w-3.5" /> {post.category}
            </Link>
            <span className="inline-flex items-center gap-1.5 text-cf-mist font-data tabular-nums">
              <Clock className="h-3.5 w-3.5 text-cf-gold" /> {mins} min read
            </span>
            <span className="inline-flex items-center gap-1.5 text-cf-mist font-data tabular-nums">
              <Eye className="h-3.5 w-3.5 text-cf-gold" /> {post.views} {post.views === 1 ? 'view' : 'views'}
            </span>
          </div>

          <h1 className="mt-5 max-w-3xl font-display font-normal text-[40px] md:text-[64px] leading-[0.98] tracking-[-0.01em] text-cf-text-strong animate-cf-reveal-up [animation-delay:80ms]">
            {post.title}
          </h1>
          {/* Gold-gradient hairline under the title — a Cinematic Finance detail */}
          <div className="mt-5 h-px w-24 bg-cf-gold-gradient opacity-60 animate-cf-reveal-up [animation-delay:140ms]" aria-hidden />

          {post.excerpt && (
            <p className="mt-5 max-w-2xl text-lg leading-relaxed text-cf-mist animate-cf-reveal-up [animation-delay:200ms]">{post.excerpt}</p>
          )}

          <div className="mt-7 flex flex-wrap items-center gap-x-6 gap-y-3 border-y border-white/[0.07] py-4 text-sm text-cf-mist animate-cf-reveal-up [animation-delay:240ms]">
            <span className="inline-flex items-center gap-2">
              <User className="h-4 w-4 text-cf-gold" />
              <Link
                href={`/blog/author/${post.author.toLowerCase().replace(/\s+/g, '-')}`}
                className="transition-colors duration-160 hover:text-cf-gold hover:underline underline-offset-2"
              >
                {post.author}
              </Link>
            </span>
            <span className="inline-flex items-center gap-2 font-data tabular-nums">
              <Calendar className="h-4 w-4 text-cf-gold" /> {fmt(post.createdAt)}
            </span>
            <div className="ml-auto">
              <ShareButtons url={canonical} title={post.title} />
            </div>
          </div>
        </div>
      </header>

      {/* Body + sidebar */}
      <div className="wrap relative px-5 py-14 md:px-8 md:py-20">
        <div className="lg:grid lg:grid-cols-[minmax(0,1fr)_280px] lg:gap-12">
          <div className="min-w-0 lg:col-start-1">
            {/* Glassmorphic article container */}
            <div className="relative rounded-xl bg-cf-glass backdrop-blur-glass border border-cf-glass-border shadow-glass overflow-hidden">
              <div className="pointer-events-none absolute inset-x-0 top-0 h-px bg-cf-gold-gradient opacity-50" />
              <div className="pointer-events-none absolute inset-0 rounded-[inherit] bg-cf-glass-glow" />
              <div className="relative p-6 md:p-10">
                {post.coverImage && (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={post.coverImage}
                    alt={post.title}
                    className="mb-10 aspect-[16/9] w-full rounded-lg border border-cf-glass-border object-cover"
                  />
                )}
                <div className="markdown-body">
                  <ReactMarkdown components={markdownComponents}>{post.content}</ReactMarkdown>
                </div>
              </div>
            </div>
          </div>

          {/* Sidebar: ToC + Popular posts */}
          <aside className="hidden lg:col-start-2 lg:block">
            <div className="sticky top-8 space-y-8">
              {toc.length > 0 && (
                <div>
                  <p className="mb-3 text-[11px] font-semibold uppercase tracking-[0.18em] text-cf-mist flex items-center gap-3">
                    <span className="block w-6 h-px bg-cf-gold opacity-70" /> On this page
                  </p>
                  <nav className="space-y-2 border-l border-white/10">
                    {toc.map((item) => (
                      <a
                        key={item.id}
                        href={`#${item.id}`}
                        className="-ml-px block border-l-2 border-transparent py-1 pl-4 text-[13px] leading-snug text-cf-mist transition-colors duration-160 hover:border-cf-gold hover:text-cf-gold"
                      >
                        {item.text}
                      </a>
                    ))}
                  </nav>
                </div>
              )}
              <PopularPosts />
            </div>
          </aside>
        </div>
      </div>

      {/* Prev / Next navigation — glassmorphic */}
      {(older || newer) && (
        <div className="relative border-t border-white/[0.06]">
          <div className="wrap grid gap-4 px-5 py-12 md:grid-cols-2 md:px-8">
            {older ? (
              <Link
                href={`/blog/${older.slug}`}
                className="group relative rounded-xl bg-cf-glass backdrop-blur-glass border border-cf-glass-border p-5 transition-all duration-240 ease-cinematic hover:-translate-y-1 hover:border-cf-gold/40 overflow-hidden"
              >
                <div className="pointer-events-none absolute inset-0 rounded-[inherit] bg-cf-glass-glow opacity-0 group-hover:opacity-100 transition-opacity duration-240" />
                <span className="relative inline-flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-[0.18em] text-cf-mist">
                  <ArrowLeft className="h-3.5 w-3.5 text-cf-gold" /> Older
                </span>
                <span className="relative block mt-2 text-[15px] font-semibold leading-snug text-cf-text-strong group-hover:text-cf-gold transition-colors duration-160 line-clamp-2">{older.title}</span>
              </Link>
            ) : (
              <div className="hidden md:block" />
            )}
            {newer && (
              <Link
                href={`/blog/${newer.slug}`}
                className="group relative rounded-xl bg-cf-glass backdrop-blur-glass border border-cf-glass-border p-5 transition-all duration-240 ease-cinematic hover:-translate-y-1 hover:border-cf-gold/40 overflow-hidden md:text-right"
              >
                <div className="pointer-events-none absolute inset-0 rounded-[inherit] bg-cf-glass-glow opacity-0 group-hover:opacity-100 transition-opacity duration-240" />
                <span className="relative inline-flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-[0.18em] text-cf-mist">
                  Newer <ArrowRight className="h-3.5 w-3.5 text-cf-gold" />
                </span>
                <span className="relative block mt-2 text-[15px] font-semibold leading-snug text-cf-text-strong group-hover:text-cf-gold transition-colors duration-160 line-clamp-2">{newer.title}</span>
              </Link>
            )}
          </div>
        </div>
      )}

      {/* Related posts — same category */}
      {related.length > 0 && (
        <div className="relative border-t border-white/[0.06]">
          <div className="wrap px-5 py-14 md:px-8 md:py-20">
            <p className="flex items-center gap-3 text-[11px] md:text-[12px] font-semibold uppercase tracking-[0.18em] text-cf-mist mb-3">
              <span className="block w-6 h-px bg-cf-gold opacity-70" />
              <Sparkles className="h-3.5 w-3.5" /> Keep reading
            </p>
            <h2 className="mb-8 font-display font-normal text-[40px] md:text-[56px] leading-[0.95] tracking-[-0.01em] text-cf-text-strong">
              More from <span className="bg-cf-gold-gradient bg-clip-text text-transparent">{post.category}</span>
            </h2>
            <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              {related.map((rp) => (
                <Link key={rp.id} href={`/blog/${rp.slug}`} className="group relative flex flex-col rounded-xl bg-cf-glass backdrop-blur-glass border border-cf-glass-border shadow-glass overflow-hidden transition-all duration-240 ease-cinematic hover:-translate-y-1 hover:border-cf-gold/40">
                  <div className="pointer-events-none absolute inset-0 rounded-[inherit] bg-cf-glass-glow opacity-0 group-hover:opacity-100 transition-opacity duration-240" />
                  <div className="relative h-36 overflow-hidden bg-cf-bg-panel">
                    {rp.coverImage ? (
                      // eslint-disable-next-line @next/next/no-img-element
                      <img src={rp.coverImage} alt={rp.title} className="h-full w-full object-cover opacity-70 transition-all duration-240 ease-cinematic group-hover:opacity-95 group-hover:scale-[1.05]" />
                    ) : (
                      <div className="flex h-full w-full items-center justify-center bg-gradient-to-br from-cf-bg-panel to-cf-bg-elevated">
                        <FileText className="h-9 w-9 text-cf-gold/30" />
                      </div>
                    )}
                    <div className="absolute inset-0 bg-gradient-to-t from-cf-bg/70 to-transparent" />
                  </div>
                  <div className="relative flex flex-1 flex-col p-5">
                    <h3 className="line-clamp-2 text-[16px] font-semibold leading-snug text-cf-text-strong transition-colors duration-160 group-hover:text-cf-gold">{rp.title}</h3>
                    {rp.excerpt && <p className="mt-2 line-clamp-2 text-[13px] leading-relaxed text-cf-mist">{rp.excerpt}</p>}
                    <div className="mt-auto flex items-center gap-2 pt-4 text-xs text-cf-text-muted font-data tabular-nums">
                      <Calendar className="h-3.5 w-3.5 text-cf-gold" /> {fmt(rp.createdAt)}
                    </div>
                  </div>
                </Link>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Breadcrumb + Newsletter */}
      <div className="wrap relative px-5 pb-24 md:px-8">
        <nav className="mb-8 flex items-center gap-1.5 text-xs text-cf-text-muted">
          <Link href="/" className="hover:text-cf-gold transition-colors duration-160">Home</Link>
          <ChevronRight className="h-3 w-3" />
          <Link href="/blog" className="hover:text-cf-gold transition-colors duration-160">Insights</Link>
          <ChevronRight className="h-3 w-3" />
          <span className="truncate text-cf-mist">{post.title}</span>
        </nav>

        <Newsletter source="blog" variant="card" />
      </div>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: safeJsonStringify(jsonLd) }}
      />
    </article>
  );
}
