import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import Link from 'next/link';
import { db } from '@/lib/db';
import { ArrowLeft, ArrowRight, Calendar, User, Tag, Clock, ChevronRight, FileText, Sparkles, Eye } from 'lucide-react';
import ReactMarkdown, { type Components } from 'react-markdown';
import { ReadingProgress, ShareButtons, ActiveTocHighlighter } from '@/components/blog-interactions';
import { Newsletter } from '@/components/newsletter';
import { PopularPosts } from '@/components/popular-posts';

type Params = { slug: string };

/** Static metadata per post so each article gets its own OG title/description.
 * The OG image is auto-generated by the `opengraph-image.tsx` route in this
 * folder — Next.js injects it automatically, so we intentionally do NOT set
 * `images` here (that would override the generated image). */
export async function generateMetadata({ params }: { params: Promise<Params> }): Promise<Metadata> {
  const { slug } = await params;
  const post = await db.blogPost.findUnique({ where: { slug } });
  if (!post || !post.published) return { title: 'Article not found' };
  return {
    title: `${post.title} — Systematic Yield Analysts`,
    description: post.excerpt ?? 'Insights from Systematic Yield Analysts',
    openGraph: {
      title: post.title,
      description: post.excerpt ?? '',
      type: 'article',
    },
    twitter: {
      card: 'summary_large_image',
      title: post.title,
      description: post.excerpt ?? '',
    },
    alternates: { canonical: `https://systematicyield.in/blog/${post.slug}` },
  };
}

/** Rough reading-time estimate from Markdown content (~200 wpm). */
function readingTime(content: string): number {
  const words = content.trim().split(/\s+/).length;
  return Math.max(1, Math.round(words / 200));
}

/** Extract H2 headings from Markdown to build a lightweight table of contents. */
function extractToc(content: string): { id: string; text: string }[] {
  const lines = content.split('\n');
  const toc: { id: string; text: string }[] = [];
  for (const line of lines) {
    const m = line.match(/^##\s+(.+?)\s*$/);
    if (m) {
      const text = m[1].replace(/[*_`]/g, '').trim();
      const id = text
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, '')
        .replace(/\s+/g, '-');
      toc.push({ id, text });
    }
  }
  return toc;
}

/** Custom react-markdown renderers: inject id attributes on h2/h3 so the ToC
 *  links and the IntersectionObserver-based active highlighter can target them. */
const markdownComponents: Components = {
  h2: ({ children }) => {
    const text = String(children);
    const id = text
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-');
    return <h2 id={id}>{children}</h2>;
  },
};

export default async function BlogPostPage({ params }: { params: Promise<Params> }) {
  const { slug } = await params;
  const post = await db.blogPost.findUnique({ where: { slug } });

  if (!post || !post.published) notFound();

  // Increment view count (fire-and-forget, non-blocking). Uses a separate
  // try/catch so a view-tracking failure never breaks page render.
  db.blogPost
    .update({ where: { id: post.id }, data: { views: { increment: 1 } } })
    .catch(() => {});

  // Fetch prev/next published posts (by creation date) + related posts (same
  // category, excluding current) for article navigation.
  const [older, newer, related] = await Promise.all([
    db.blogPost.findFirst({
      where: { published: true, createdAt: { lt: post.createdAt } },
      orderBy: { createdAt: 'desc' },
      select: { slug: true, title: true },
    }),
    db.blogPost.findFirst({
      where: { published: true, createdAt: { gt: post.createdAt } },
      orderBy: { createdAt: 'asc' },
      select: { slug: true, title: true },
    }),
    db.blogPost.findMany({
      where: { published: true, category: post.category, slug: { not: post.slug } },
      orderBy: { createdAt: 'desc' },
      take: 3,
      select: {
        id: true, slug: true, title: true, excerpt: true, coverImage: true,
        category: true, author: true, createdAt: true,
      },
    }),
  ]);

  const fmt = (d: Date) =>
    d.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' });
  const mins = readingTime(post.content);
  const toc = extractToc(post.content);
  const canonical = `https://systematicyield.in/blog/${post.slug}`;

  // JSON-LD Article schema for rich results.
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: post.title,
    description: post.excerpt ?? '',
    datePublished: post.createdAt.toISOString(),
    dateModified: post.updatedAt.toISOString(),
    author: { '@type': 'Organization', name: post.author },
    publisher: { '@type': 'Organization', name: 'Systematic Yield Analysts' },
    mainEntityOfPage: canonical,
    image: post.coverImage ? [post.coverImage] : undefined,
  };

  return (
    <article className="min-h-screen bg-[#070B14] text-[#E8EBF2]">
      <ReadingProgress />
      <ActiveTocHighlighter />

      {/* Hero */}
      <header className="relative overflow-hidden border-b border-white/[0.06]">
        <div className="blog-hero-glow" aria-hidden />
        <div className="wrap relative px-5 py-16 md:px-8 md:py-24">
          <Link
            href="/blog"
            className="mb-8 inline-flex items-center gap-2 text-sm text-[#98A2B8] transition-colors hover:text-[#E2B15C]"
          >
            <ArrowLeft className="h-4 w-4" /> All Insights
          </Link>

          <div className="flex flex-wrap items-center gap-3 text-xs">
            <span className="inline-flex items-center gap-1.5 rounded-full bg-[#E2B15C]/10 px-3 py-1 text-[#E2B15C] ring-1 ring-[#E2B15C]/25">
              <Tag className="h-3.5 w-3.5" /> {post.category}
            </span>
            <span className="inline-flex items-center gap-1.5 text-[#98A2B8]">
              <Clock className="h-3.5 w-3.5" /> {mins} min read
            </span>
            <span className="inline-flex items-center gap-1.5 text-[#98A2B8]">
              <Eye className="h-3.5 w-3.5 text-[#E2B15C]" /> {post.views} {post.views === 1 ? 'view' : 'views'}
            </span>
          </div>

          <h1 className="mt-5 max-w-3xl font-[family-name:var(--font-fraunces)] text-3xl font-semibold leading-[1.12] md:text-5xl">
            {post.title}
          </h1>

          {post.excerpt && (
            <p className="mt-5 max-w-2xl text-lg leading-relaxed text-[#98A2B8]">{post.excerpt}</p>
          )}

          <div className="mt-7 flex flex-wrap items-center gap-x-6 gap-y-3 border-y border-white/[0.08] py-4 text-sm text-[#98A2B8]">
            <span className="inline-flex items-center gap-2">
              <User className="h-4 w-4 text-[#E2B15C]" />
              <Link
                href={`/blog/author/${post.author.toLowerCase().replace(/\s+/g, '-')}`}
                className="transition-colors hover:text-[#E2B15C] hover:underline underline-offset-2"
              >
                {post.author}
              </Link>
            </span>
            <span className="inline-flex items-center gap-2">
              <Calendar className="h-4 w-4 text-[#E2B15C]" /> {fmt(post.createdAt)}
            </span>
            <div className="ml-auto">
              <ShareButtons url={canonical} title={post.title} />
            </div>
          </div>
        </div>
      </header>

      {/* Body + sidebar */}
      <div className="wrap px-5 py-14 md:px-8 md:py-20">
        <div className="lg:grid lg:grid-cols-[minmax(0,1fr)_280px] lg:gap-12">
          <div className="min-w-0 lg:col-start-1">
            {post.coverImage && (
              <img
                src={post.coverImage}
                alt={post.title}
                className="mb-10 aspect-[16/9] w-full rounded-xl border border-white/10 object-cover"
              />
            )}

            {/* react-markdown escapes HTML by default and only renders known nodes,
                so untrusted Markdown content can't inject scripts. Custom h2
                renderer injects id attributes so the ToC + active highlighter work. */}
            <div className="markdown-body">
              <ReactMarkdown components={markdownComponents}>{post.content}</ReactMarkdown>
            </div>
          </div>

          {/* Sidebar: Table of contents + Popular posts (sticky on desktop) */}
          <aside className="hidden lg:col-start-2 lg:block">
            <div className="sticky top-8 space-y-8">
              {toc.length > 0 && (
                <div>
                  <p className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-[#98A2B8]">
                    On this page
                  </p>
                  <nav className="space-y-2 border-l border-white/10">
                    {toc.map((item) => (
                      <a
                        key={item.id}
                        href={`#${item.id}`}
                        className="-ml-px block border-l-2 border-transparent py-1 pl-4 text-[13px] leading-snug text-[#98A2B8] transition-colors hover:border-[#E2B15C] hover:text-[#E2B15C]"
                      >
                        {item.text}
                      </a>
                    ))}
                  </nav>
                </div>
              )}
              <PopularPosts />
            </div>
          </aside>
        </div>
      </div>

      {/* Prev / Next navigation */}
      {(older || newer) && (
        <div className="border-t border-white/[0.06]">
          <div className="wrap grid gap-4 px-5 py-12 md:grid-cols-2 md:px-8">
            {older ? (
              <Link
                href={`/blog/${older.slug}`}
                className="post-nav post-nav-prev group"
              >
                <span className="post-nav-label">
                  <ArrowLeft className="h-3.5 w-3.5" /> Older
                </span>
                <span className="post-nav-title">{older.title}</span>
              </Link>
            ) : (
              <div className="hidden md:block" />
            )}
            {newer && (
              <Link
                href={`/blog/${newer.slug}`}
                className="post-nav post-nav-next group md:text-right"
              >
                <span className="post-nav-label">
                  Newer <ArrowRight className="h-3.5 w-3.5" />
                </span>
                <span className="post-nav-title">{newer.title}</span>
              </Link>
            )}
          </div>
        </div>
      )}

      {/* Related posts — same category, keeps readers in the funnel */}
      {related.length > 0 && (
        <div className="border-t border-white/[0.06]">
          <div className="wrap px-5 py-14 md:px-8 md:py-20">
            <p className="eyebrow mb-3">
              <Sparkles className="h-3.5 w-3.5" /> Keep reading
            </p>
            <h2 className="mb-8 font-[family-name:var(--font-fraunces)] text-2xl font-semibold text-[#E8EBF2] md:text-3xl">
              More from <em>{post.category}</em>
            </h2>
            <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              {related.map((rp) => (
                <Link key={rp.id} href={`/blog/${rp.slug}`} className="blog-card group flex flex-col">
                  <div className="blog-card-cover">
                    {rp.coverImage ? (
                      <img
                        src={rp.coverImage}
                        alt={rp.title}
                        className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"
                      />
                    ) : (
                      <div className="flex h-full w-full items-center justify-center bg-gradient-to-br from-[#0C1322] to-[#0A0F1C]">
                        <FileText className="h-9 w-9 text-[#E2B15C]/40" />
                      </div>
                    )}
                  </div>
                  <div className="flex flex-1 flex-col p-5">
                    <h3 className="line-clamp-2 font-[family-name:var(--font-fraunces)] text-[16px] font-semibold leading-snug text-[#E8EBF2] transition-colors group-hover:text-[#E2B15C]">
                      {rp.title}
                    </h3>
                    {rp.excerpt && (
                      <p className="mt-2 line-clamp-2 text-[13px] leading-relaxed text-[#98A2B8]">
                        {rp.excerpt}
                      </p>
                    )}
                    <div className="mt-auto flex items-center gap-2 pt-4 text-xs text-[#525C70]">
                      <Calendar className="h-3.5 w-3.5" />
                      {fmt(rp.createdAt)}
                    </div>
                  </div>
                </Link>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Breadcrumb + Newsletter */}
      <div className="wrap px-5 pb-24 md:px-8">
        <nav className="mb-8 flex items-center gap-1.5 text-xs text-[#525C70]">
          <Link href="/" className="hover:text-[#E2B15C]">Home</Link>
          <ChevronRight className="h-3 w-3" />
          <Link href="/blog" className="hover:text-[#E2B15C]">Insights</Link>
          <ChevronRight className="h-3 w-3" />
          <span className="truncate text-[#98A2B8]">{post.title}</span>
        </nav>

        <Newsletter source="blog" variant="card" />
      </div>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
    </article>
  );
}
